[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = [] }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt" }

[[language]]
name = "qml"
auto-format = true
formatter = { command = "qmlformat" }
